### ISSUE TITLE
Trying to create sqoop_commands.sh based on example.yaml file gives error

### ISSUE THREAD

**Issue by hetacharya12** [datadudes/sisyphus#7]
Hi,

Thanks for the great work with cornet. I was trying to run cornet based on the information given in the readme file but get the following errors while running cornet example.yaml > sqoop_commands.sh 

Traceback (most recent call last):
  File "/home/usr/.local/bin/cornet", line 11, in <module>
    sys.exit(cli())
  File "/home/usr/.local/lib/python2.7/site-packages/click/core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "/home/usr/.local/lib/python2.7/site-packages/click/core.py", line 590, in main
    rv = self.invoke(ctx)
  File "/home/usr/.local/lib/python2.7/site-packages/click/core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/usr/.local/lib/python2.7/site-packages/click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "/home/usr/.local/lib/python2.7/site-packages/cornet/main.py", line 39, in cli
    for task in TaskConfig.load(config_file):
  File "/home/usr/.local/lib/python2.7/site-packages/cornet/task_config.py", line 44, in load
    global_conf = conf['global']
KeyError: 'global'

**Comment by DonDebonair** [comment]
What is in your example.yaml?

**Comment by hetacharya12** [comment]
source:
    host: localhost
    port: 5432
    db: portfoliodb
    user: postgres
    password: (password)
    driver: org.postgresql.Driver

**Comment by DonDebonair** [comment]
Can you copy/paste it in code tags, because what you posted now seems like invalid YAML.

**Comment by hetacharya12** [comment]
Apologies, attaching the file.
[exampleYAMLfile.zip](https://github.com/datadudes/cornet/files/2383471/exampleYAMLfile.zip)

**Comment by hetacharya12** [comment]
Found the issue with YAML file :), although I get the following error.

  File "c:\users\hetac\appdata\local\programs\python\python36\lib\site-packages\cornet\task_config.py", line 44, in load
    **global_conf = conf['global']
TypeError: list indices must be integers or slices, not str**

**Comment by DonDebonair** [comment]
@hetacharya12 I've found the error. It seems that the example in the README is not correct, and there's also a bug in the code that prevents you from using a config file with no `global` section.

The example from the README should actually look like this:

```
tasks:
  - source:
      host: db-server.example.com
      port: 5432
      db: portal
      user: marcel
      password: my-secret-password
      driver: postgresql
    hive:
      db: source
```

As you can see, there should be a `tasks` section, under which there is a list of objects that describe the different DBs you want to import.

To work around the `global` key missing, you can add an empty `global` object. Your own YAML file should look like this then:

```
global: {}
tasks:
  - source:
      host: localhost
      port: 5432
      db: portfoliodb
      user: postgres
      password: my-secret-password
      driver: postgres
    hive:
      db: source
```

I can see if I can push a fix for the missing `global` key this weekend. In the meanwhile you can try out my suggestions.
